In [1]:
import os

from dbase.DataAPI.ThetaData import list_dates, set_use_proxy, retrieve_chain_bulk, list_contracts, retrieve_eod_ohlc
from trade.datamanager.utils.date import _sync_date, LIST_DATE_CACHE
from trade.datamanager.option_spot import OptionSpotDataManager
from trade.datamanager.loaders import load_full_option_data 
os.environ["THETADATA_USE_V3"] = "true"
set_use_proxy("")

/Users/chiemelienwanisobi/miniconda3/envs/openbb_new_use/lib/python3.11/site-packages/requests/__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(

2026-05-03 21:49:32 trade.helpers.Logging INFO: Logging Root Directory: /Users/chiemelienwanisobi/cloned_repos/FinanceDatabase/logs
2026-05-03 21:49:32 [test] trade.helpers.clear_cache INFO: No expired caches to delete on 2026-05-03.
2026-05-03 21:49:34 [test] dbase.DataAPI.ThetaData.proxy INFO: Refreshed proxy URL: http://34.229.99.136:5500/thetadata
2026-05-03 21:49:34 [test] dbase.DataAPI.ThetaData.proxy INFO: Using Proxy URL: http://34.229.99.136:5500/thetadata
2026-05-03 21:49:38 [test] dbase.DataAPI.ThetaData.proxy INFO: Proxy URL has been unset.

In [2]:
{
    "symbol": "QQQ",
    "start_date": "20231227",
    "end_date": "20240208",
    "expiration": "20240328",
    "strike": "440.00",
    "right": "C",
    "url": "http://localhost:25503/v3/option/history/eod?symbol=QQQ&start_date=20231227&end_date=20240208&expiration=20240328&strike=440.00&right=C",
}

{'symbol': 'QQQ',
 'start_date': '20231227',
 'end_date': '20240208',
 'expiration': '20240328',
 'strike': '440.00',
 'right': 'C',
 'url': 'http://localhost:25503/v3/option/history/eod?symbol=QQQ&start_date=20231227&end_date=20240208&expiration=20240328&strike=440.00&right=C'}

In [13]:
symbol = "QQQ"
start_date = "2023-09-27"
end_date = "2024-03-28"
opt_params = {
    "strike": 440.00,
    "right": "C",
    "expiration": "2024-03-28",
}
OptionSpotDataManager(symbol=symbol).get_option_spot_timeseries(
    start_date=start_date,
    end_date=end_date,
    **opt_params,
).timeseries

2026-05-03 21:51:16 [test] trade.datamanager.utils INFO: Using cached date range for 2023-09-27 00:00:00 - 2024-03-28 00:00:00 and option tick QQQ20240328C440
2026-05-03 21:51:16 [test] trade.datamanager.utils INFO: No unfilled gaps within requested range for key symbol:QQQ|interval:eod|artifact_type:option_spot|series_id:hist|endpoint_source:EOD|expiration:20240328T000000|right:C|strike:440. Fully covered: True
2026-05-03 21:51:16 [test] trade.datamanager.utils INFO: Cache hit for timeseries data structure key: symbol:QQQ|interval:eod|artifact_type:option_spot|series_id:hist|endpoint_source:EOD|expiration:20240328T000000|right:C|strike:440
2026-05-03 21:51:16 [test] trade.datamanager.utils INFO: Sanitizing data from 2023-09-27 00:00:00 to 2024-03-28 00:00:00...
2026-05-03 21:51:16 [test] trade.datamanager.option_spot INFO: Cache hit for option spot timeseries key: symbol:QQQ|interval:eod|artifact_type:option_spot|series_id:hist|endpoint_source:EOD|expiration:20240328T000000|right:C|strike:440

,open,high,low,close,volume,count,bid_size,closebid,ask_size,closeask,midpoint,weighted_midpoint
datetime,,,,,,,,,,,,
2023-09-27,1.08,1.19,1.08,1.19,10.0,2.0,500.0,1.13,500.0,1.26,1.195,1.195000
2023-09-28,0.00,0.00,0.00,0.00,0.0,0.0,515.0,1.18,501.0,1.38,1.280,1.278622
2023-09-29,1.21,1.28,1.20,1.20,29.0,4.0,505.0,1.20,512.0,1.33,1.265,1.265447
2023-10-02,1.37,1.37,1.37,1.37,25.0,1.0,118.0,1.36,248.0,1.46,1.410,1.427760
2023-10-03,1.23,1.23,1.23,1.23,10.0,1.0,501.0,1.12,270.0,1.26,1.190,1.169027
...,...,...,...,...,...,...,...,...,...,...,...,...
2024-03-22,6.89,8.69,6.55,7.38,817.0,135.0,1.0,7.33,9.0,7.46,7.395,7.447000
2024-03-25,5.13,7.22,4.64,6.05,1909.0,182.0,1.0,6.04,5.0,6.17,6.105,6.148333
2024-03-26,6.91,7.89,4.38,4.40,1193.0,198.0,1.0,4.86,20.0,4.97,4.915,4.964762
2024-03-27,6.86,6.86,3.03,5.34,6910.0,741.0,2.0,5.27,1.0,5.41,5.340,5.316667
2024-03-28,4.90,5.55,3.75,4.09,2767.0,518.0,6.0,2.60,30.0,6.50,4.550,5.850000

In [14]:
res = load_full_option_data(
    symbol=symbol,
    start_date=start_date,
    end_date=end_date,
    **opt_params,
)

2026-05-03 21:51:21 [test] trade.datamanager.vars INFO: Timeseries for QQQ already loaded.
2026-05-03 21:51:21 [test] trade.datamanager.dividend INFO: Using provided dividend_type: DivType.DISCRETE
2026-05-03 21:51:21 [test] trade.datamanager.dividend INFO: Fetching discrete dividend schedule timeseries for QQQ from 2023-09-27 00:00:00 to 2024-03-28 00:00:00 with maturity 2024-03-28 00:00:00
2026-05-03 21:51:21 [test] trade.datamanager.utils INFO: Covered range 2023-11-27 to 2024-02-08 does not span requested range 2023-09-27 to 2024-03-28 for key: symbol:QQQ|interval:eod|artifact_type:divs|series_id:hist|current_state:SCHEDULE_TIMESERIES|lookback_years:1|maturity:2024-03-28|method:CONSTANT|undo_adjust:1.
2026-05-03 21:51:21 [test] trade.datamanager.utils INFO: Cache partially covers requested date range for timeseries data structure. Key: symbol:QQQ|interval:eod|artifact_type:divs|series_id:hist|current_state:SCHEDULE_TIMESERIES|lookback_years:1|maturity:2024-03-28|method:CONSTANT|undo_adjust:1. Dates still needed: [Timestamp('2023-09-27 00:00:00'), Timestamp('2023-09-28 00:00:00'), Timestamp('2023-09-29 00:00:00'), Timestamp('2023-10-02 00:00:00'), Timestamp('2023-10-03 00:00:00'), Timestamp('2023-10-04 00:00:00'), Timestamp('2023-10-05 00:00:00'), Timestamp('2023-10-06 00:00:00'), Timestamp('2023-10-09 00:00:00'), Timestamp('2023-10-10 00:00:00'), Timestamp('2023-10-11 00:00:00'), Timestamp('2023-10-12 00:00:00'), Timestamp('2023-10-13 00:00:00'), Timestamp('2023-10-16 00:00:00'), Timestamp('2023-10-17 00:00:00'), Timestamp('2023-10-18 00:00:00'), Timestamp('2023-10-19 00:00:00'), Timestamp('2023-10-20 00:00:00'), Timestamp('2023-10-23 00:00:00'), Timestamp('2023-10-24 00:00:00'), Timestamp('2023-10-25 00:00:00'), Timestamp('2023-10-26 00:00:00'), Timestamp('2023-10-27 00:00:00'), Timestamp('2023-10-30 00:00:00'), Timestamp('2023-10-31 00:00:00'), Timestamp('2023-11-01 00:00:00'), Timestamp('2023-11-02 00:00:00'), Timestamp('2023-11-03 00:00:00'), Timestamp('2023-11-06 00:00:00'), Timestamp('2023-11-07 00:00:00'), Timestamp('2023-11-08 00:00:00'), Timestamp('2023-11-09 00:00:00'), Timestamp('2023-11-10 00:00:00'), Timestamp('2023-11-13 00:00:00'), Timestamp('2023-11-14 00:00:00'), Timestamp('2023-11-15 00:00:00'), Timestamp('2023-11-16 00:00:00'), Timestamp('2023-11-17 00:00:00'), Timestamp('2023-11-20 00:00:00'), Timestamp('2023-11-21 00:00:00'), Timestamp('2023-11-22 00:00:00'), Timestamp('2023-11-24 00:00:00'), Timestamp('2024-02-09 00:00:00'), Timestamp('2024-02-12 00:00:00'), Timestamp('2024-02-13 00:00:00'), Timestamp('2024-02-14 00:00:00'), Timestamp('2024-02-15 00:00:00'), Timestamp('2024-02-16 00:00:00'), Timestamp('2024-02-20 00:00:00'), Timestamp('2024-02-21 00:00:00'), Timestamp('2024-02-22 00:00:00'), Timestamp('2024-02-23 00:00:00'), Timestamp('2024-02-26 00:00:00'), Timestamp('2024-02-27 00:00:00'), Timestamp('2024-02-28 00:00:00'), Timestamp('2024-02-29 00:00:00'), Timestamp('2024-03-01 00:00:00'), Timestamp('2024-03-04 00:00:00'), Timestamp('2024-03-05 00:00:00'), Timestamp('2024-03-06 00:00:00'), Timestamp('2024-03-07 00:00:00'), Timestamp('2024-03-08 00:00:00'), Timestamp('2024-03-11 00:00:00'), Timestamp('2024-03-12 00:00:00'), Timestamp('2024-03-13 00:00:00'), Timestamp('2024-03-14 00:00:00'), Timestamp('2024-03-15 00:00:00'), Timestamp('2024-03-18 00:00:00'), Timestamp('2024-03-19 00:00:00'), Timestamp('2024-03-20 00:00:00'), Timestamp('2024-03-21 00:00:00'), Timestamp('2024-03-22 00:00:00'), Timestamp('2024-03-25 00:00:00'), Timestamp('2024-03-26 00:00:00'), Timestamp('2024-03-27 00:00:00'), Timestamp('2024-03-28 00:00:00')]
2026-05-03 21:51:21 [test] trade.datamanager.vars INFO: Timeseries for QQQ already loaded.
2026-05-03 21:51:21 [test] trade.datamanager.dividend INFO: Cache hit for key: symbol:QQQ|interval:na|artifact_type:divs|series_id:hist|current_state:SCHEDULE|lookback_years:1|method:CONSTANT|vendor:YFINANCE
2026-05-03 21:51:21 [test] trade.datamanager.dividend INFO: Cache fully covers requested date range. Key: symbol:QQQ|interval:na|artifact_type:divs|series_id:hist|current_state:SCHEDULE|lookback_years:1|method:CONSTANT|vendor:YFINANCE
2026-05-03 21:51:21 [test] trade.datamanager.utils INFO: No unfilled gaps within requested range for key QQQ. Fully covered: True
2026-05-03 21:51:21 [test] trade.datamanager.utils INFO: Cache hit for timeseries data structure key: QQQ
2026-05-03 21:51:21 [test] trade.datamanager.utils INFO: Sanitizing data from 2018-01-02 00:00:00 to 2026-05-01 21:49:38.330679...
2026-05-03 21:51:21 [test] trade.datamanager.utils INFO: Sanitizing data from 2023-09-27 00:00:00 to 2024-03-28 00:00:00...
2026-05-03 21:51:21 [test] trade.datamanager.utils INFO: Max date 2024-03-28 for key: symbol:QQQ|interval:eod|artifact_type:divs|series_id:hist|current_state:SCHEDULE_TIMESERIES|lookback_years:1|maturity:2024-03-28|method:CONSTANT|undo_adjust:1 is not today. Skipping today's data check.
2026-05-03 21:51:21 [test] trade.datamanager.utils INFO: Caching timeseries data structure for key: symbol:QQQ|interval:eod|artifact_type:divs|series_id:hist|current_state:SCHEDULE_TIMESERIES|lookback_years:1|maturity:2024-03-28|method:CONSTANT|undo_adjust:1 with date range 2023-09-27 to 2024-03-28, missing dates within range: [], checked-missing dates: []
2026-05-03 21:51:21 [test] trade.datamanager.utils INFO: No unfilled gaps within requested range for key symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D. Fully covered: True
2026-05-03 21:51:21 [test] trade.datamanager.utils INFO: Cache hit for timeseries data structure key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D
2026-05-03 21:51:21 [test] trade.datamanager.utils INFO: Sanitizing data from 2023-09-27 00:00:00 to 2024-03-28 00:00:00...
2026-05-03 21:51:21 [test] trade.datamanager.rates INFO: Cache fully covers requested date range for risk-free rate timeseries. Key: symbol:^IRX|interval:eod|artifact_type:rates|series_id:hist|fn_interval:1D
2026-05-03 21:51:21 [test] trade.datamanager.utils INFO: Sanitizing data from 2023-09-27 to 2024-03-28...
2026-05-03 21:51:21 [test] trade.datamanager.vars INFO: Timeseries for QQQ already loaded.
2026-05-03 21:51:21 [test] trade.datamanager.utils INFO: No unfilled gaps within requested range for key QQQ. Fully covered: True
2026-05-03 21:51:21 [test] trade.datamanager.utils INFO: Cache hit for timeseries data structure key: QQQ
2026-05-03 21:51:21 [test] trade.datamanager.utils INFO: Sanitizing data from 2023-09-27 00:00:00 to 2024-03-28 00:00:00...
2026-05-03 21:51:21 [test] trade.datamanager.utils INFO: Sanitizing data from 2023-09-27 00:00:00 to 2024-03-28 00:00:00...
2026-05-03 21:51:21 [test] trade.datamanager.vars INFO: Timeseries for QQQ already loaded.
2026-05-03 21:51:21 [test] trade.datamanager.utils INFO: Covered range 2023-11-27 to 2024-02-08 does not span requested range 2023-09-27 to 2024-03-28 for key: symbol:QQQ|interval:eod|artifact_type:forward|series_id:hist|dividend_type:DISCRETE|maturity:2024-03-28|use_chain_spot:1.
2026-05-03 21:51:21 [test] trade.datamanager.utils INFO: Cache partially covers requested date range for timeseries data structure. Key: symbol:QQQ|interval:eod|artifact_type:forward|series_id:hist|dividend_type:DISCRETE|maturity:2024-03-28|use_chain_spot:1. Dates still needed: [Timestamp('2023-09-27 00:00:00'), Timestamp('2023-09-28 00:00:00'), Timestamp('2023-09-29 00:00:00'), Timestamp('2023-10-02 00:00:00'), Timestamp('2023-10-03 00:00:00'), Timestamp('2023-10-04 00:00:00'), Timestamp('2023-10-05 00:00:00'), Timestamp('2023-10-06 00:00:00'), Timestamp('2023-10-09 00:00:00'), Timestamp('2023-10-10 00:00:00'), Timestamp('2023-10-11 00:00:00'), Timestamp('2023-10-12 00:00:00'), Timestamp('2023-10-13 00:00:00'), Timestamp('2023-10-16 00:00:00'), Timestamp('2023-10-17 00:00:00'), Timestamp('2023-10-18 00:00:00'), Timestamp('2023-10-19 00:00:00'), Timestamp('2023-10-20 00:00:00'), Timestamp('2023-10-23 00:00:00'), Timestamp('2023-10-24 00:00:00'), Timestamp('2023-10-25 00:00:00'), Timestamp('2023-10-26 00:00:00'), Timestamp('2023-10-27 00:00:00'), Timestamp('2023-10-30 00:00:00'), Timestamp('2023-10-31 00:00:00'), Timestamp('2023-11-01 00:00:00'), Timestamp('2023-11-02 00:00:00'), Timestamp('2023-11-03 00:00:00'), Timestamp('2023-11-06 00:00:00'), Timestamp('2023-11-07 00:00:00'), Timestamp('2023-11-08 00:00:00'), Timestamp('2023-11-09 00:00:00'), Timestamp('2023-11-10 00:00:00'), Timestamp('2023-11-13 00:00:00'), Timestamp('2023-11-14 00:00:00'), Timestamp('2023-11-15 00:00:00'), Timestamp('2023-11-16 00:00:00'), Timestamp('2023-11-17 00:00:00'), Timestamp('2023-11-20 00:00:00'), Timestamp('2023-11-21 00:00:00'), Timestamp('2023-11-22 00:00:00'), Timestamp('2023-11-24 00:00:00'), Timestamp('2024-02-09 00:00:00'), Timestamp('2024-02-12 00:00:00'), Timestamp('2024-02-13 00:00:00'), Timestamp('2024-02-14 00:00:00'), Timestamp('2024-02-15 00:00:00'), Timestamp('2024-02-16 00:00:00'), Timestamp('2024-02-20 00:00:00'), Timestamp('2024-02-21 00:00:00'), Timestamp('2024-02-22 00:00:00'), Timestamp('2024-02-23 00:00:00'), Timestamp('2024-02-26 00:00:00'), Timestamp('2024-02-27 00:00:00'), Timestamp('2024-02-28 00:00:00'), Timestamp('2024-02-29 00:00:00'), Timestamp('2024-03-01 00:00:00'), Timestamp('2024-03-04 00:00:00'), Timestamp('2024-03-05 00:00:00'), Timestamp('2024-03-06 00:00:00'), Timestamp('2024-03-07 00:00:00'), Timestamp('2024-03-08 00:00:00'), Timestamp('2024-03-11 00:00:00'), Timestamp('2024-03-12 00:00:00'), Timestamp('2024-03-13 00:00:00'), Timestamp('2024-03-14 00:00:00'), Timestamp('2024-03-15 00:00:00'), Timestamp('2024-03-18 00:00:00'), Timestamp('2024-03-19 00:00:00'), Timestamp('2024-03-20 00:00:00'), Timestamp('2024-03-21 00:00:00'), Timestamp('2024-03-22 00:00:00'), Timestamp('2024-03-25 00:00:00'), Timestamp('2024-03-26 00:00:00'), Timestamp('2024-03-27 00:00:00'), Timestamp('2024-03-28 00:00:00')]
2026-05-03 21:51:21 [test] trade.datamanager.utils INFO: Max date 2024-03-28 for key: symbol:QQQ|interval:eod|artifact_type:forward|series_id:hist|dividend_type:DISCRETE|maturity:2024-03-28|use_chain_spot:1 is not today. Skipping today's data check.
2026-05-03 21:51:21 [test] trade.datamanager.utils INFO: Caching timeseries data structure for key: symbol:QQQ|interval:eod|artifact_type:forward|series_id:hist|dividend_type:DISCRETE|maturity:2024-03-28|use_chain_spot:1 with date range 2023-09-27 to 2024-03-28, missing dates within range: [], checked-missing dates: []
2026-05-03 21:51:21 [test] trade.datamanager.utils INFO: Sanitizing data from 2023-09-27 00:00:00 to 2024-03-28 00:00:00...
2026-05-03 21:51:21 [test] trade.datamanager.utils INFO: Using cached date range for 2023-09-27 00:00:00 - 2024-03-28 00:00:00 and option tick QQQ20240328C440
2026-05-03 21:51:21 [test] trade.datamanager.utils INFO: No unfilled gaps within requested range for key symbol:QQQ|interval:eod|artifact_type:option_spot|series_id:hist|endpoint_source:EOD|expiration:20240328T000000|right:C|strike:440. Fully covered: True
2026-05-03 21:51:21 [test] trade.datamanager.utils INFO: Cache hit for timeseries data structure key: symbol:QQQ|interval:eod|artifact_type:option_spot|series_id:hist|endpoint_source:EOD|expiration:20240328T000000|right:C|strike:440
2026-05-03 21:51:21 [test] trade.datamanager.utils INFO: Sanitizing data from 2023-09-27 00:00:00 to 2024-03-28 00:00:00...
2026-05-03 21:51:21 [test] trade.datamanager.option_spot INFO: Cache hit for option spot timeseries key: symbol:QQQ|interval:eod|artifact_type:option_spot|series_id:hist|endpoint_source:EOD|expiration:20240328T000000|right:C|strike:440
2026-05-03 21:51:21 [test] trade.datamanager.vol INFO: VolDm Using specified dividend type: DivType.DISCRETE
2026-05-03 21:51:21 [test] trade.datamanager.vol INFO: VolDm Using model price: ModelPrice.MIDPOINT
2026-05-03 21:51:21 [test] trade.datamanager.utils INFO: Using cached date range for 2023-09-27 00:00:00 - 2024-03-28 00:00:00 and option tick QQQ20240328C440
2026-05-03 21:51:21 [test] trade.datamanager.utils INFO: Covered range 2023-11-27 to 2024-02-08 does not span requested range 2023-09-27 to 2024-03-28 for key: symbol:QQQ|interval:eod|artifact_type:iv|series_id:hist|american:1|dividend_type:discrete|endpoint_source:eod|expiration:20240328T000000|model_price:midpoint|n_steps:100|option_pricing_model:Binomial|right:C|strike:440|volatility_model:market.
2026-05-03 21:51:21 [test] trade.datamanager.utils INFO: Cache partially covers requested date range for timeseries data structure. Key: symbol:QQQ|interval:eod|artifact_type:iv|series_id:hist|american:1|dividend_type:discrete|endpoint_source:eod|expiration:20240328T000000|model_price:midpoint|n_steps:100|option_pricing_model:Binomial|right:C|strike:440|volatility_model:market. Dates still needed: [Timestamp('2023-09-27 00:00:00'), Timestamp('2023-09-28 00:00:00'), Timestamp('2023-09-29 00:00:00'), Timestamp('2023-10-02 00:00:00'), Timestamp('2023-10-03 00:00:00'), Timestamp('2023-10-04 00:00:00'), Timestamp('2023-10-05 00:00:00'), Timestamp('2023-10-06 00:00:00'), Timestamp('2023-10-09 00:00:00'), Timestamp('2023-10-10 00:00:00'), Timestamp('2023-10-11 00:00:00'), Timestamp('2023-10-12 00:00:00'), Timestamp('2023-10-13 00:00:00'), Timestamp('2023-10-16 00:00:00'), Timestamp('2023-10-17 00:00:00'), Timestamp('2023-10-18 00:00:00'), Timestamp('2023-10-19 00:00:00'), Timestamp('2023-10-20 00:00:00'), Timestamp('2023-10-23 00:00:00'), Timestamp('2023-10-24 00:00:00'), Timestamp('2023-10-25 00:00:00'), Timestamp('2023-10-26 00:00:00'), Timestamp('2023-10-27 00:00:00'), Timestamp('2023-10-30 00:00:00'), Timestamp('2023-10-31 00:00:00'), Timestamp('2023-11-01 00:00:00'), Timestamp('2023-11-02 00:00:00'), Timestamp('2023-11-03 00:00:00'), Timestamp('2023-11-06 00:00:00'), Timestamp('2023-11-07 00:00:00'), Timestamp('2023-11-08 00:00:00'), Timestamp('2023-11-09 00:00:00'), Timestamp('2023-11-10 00:00:00'), Timestamp('2023-11-13 00:00:00'), Timestamp('2023-11-14 00:00:00'), Timestamp('2023-11-15 00:00:00'), Timestamp('2023-11-16 00:00:00'), Timestamp('2023-11-17 00:00:00'), Timestamp('2023-11-20 00:00:00'), Timestamp('2023-11-21 00:00:00'), Timestamp('2023-11-22 00:00:00'), Timestamp('2023-11-24 00:00:00'), Timestamp('2024-02-09 00:00:00'), Timestamp('2024-02-12 00:00:00'), Timestamp('2024-02-13 00:00:00'), Timestamp('2024-02-14 00:00:00'), Timestamp('2024-02-15 00:00:00'), Timestamp('2024-02-16 00:00:00'), Timestamp('2024-02-20 00:00:00'), Timestamp('2024-02-21 00:00:00'), Timestamp('2024-02-22 00:00:00'), Timestamp('2024-02-23 00:00:00'), Timestamp('2024-02-26 00:00:00'), Timestamp('2024-02-27 00:00:00'), Timestamp('2024-02-28 00:00:00'), Timestamp('2024-02-29 00:00:00'), Timestamp('2024-03-01 00:00:00'), Timestamp('2024-03-04 00:00:00'), Timestamp('2024-03-05 00:00:00'), Timestamp('2024-03-06 00:00:00'), Timestamp('2024-03-07 00:00:00'), Timestamp('2024-03-08 00:00:00'), Timestamp('2024-03-11 00:00:00'), Timestamp('2024-03-12 00:00:00'), Timestamp('2024-03-13 00:00:00'), Timestamp('2024-03-14 00:00:00'), Timestamp('2024-03-15 00:00:00'), Timestamp('2024-03-18 00:00:00'), Timestamp('2024-03-19 00:00:00'), Timestamp('2024-03-20 00:00:00'), Timestamp('2024-03-21 00:00:00'), Timestamp('2024-03-22 00:00:00'), Timestamp('2024-03-25 00:00:00'), Timestamp('2024-03-26 00:00:00'), Timestamp('2024-03-27 00:00:00'), Timestamp('2024-03-28 00:00:00')]
2026-05-03 21:51:21 [test] trade.datamanager.utils INFO: Cache partially covers requested date range. Key: symbol:QQQ|interval:eod|artifact_type:iv|series_id:hist|american:1|dividend_type:discrete|endpoint_source:eod|expiration:20240328T000000|model_price:midpoint|n_steps:100|option_pricing_model:Binomial|right:C|strike:440|volatility_model:market. Fetching missing dates.
2026-05-03 21:51:21 [test] trade.datamanager.utils INFO: No data requested to load in _load_model_data_timeseries(). Option: Symbol=QQQ, exp=2024-03-28 00:00:00, strike=440.0 right=C Load bools: d=False, r=False, s=False, f=False, opt_spot=False, vol=False, greek=False
2026-05-03 21:51:22 [test] trade.datamanager.utils INFO: Max date 2024-03-28 for key: symbol:QQQ|interval:eod|artifact_type:iv|series_id:hist|american:1|dividend_type:discrete|endpoint_source:eod|expiration:20240328T000000|model_price:midpoint|n_steps:100|option_pricing_model:Binomial|right:C|strike:440|volatility_model:market is not today. Skipping today's data check.
2026-05-03 21:51:22 [test] trade.datamanager.utils INFO: Caching timeseries data structure for key: symbol:QQQ|interval:eod|artifact_type:iv|series_id:hist|american:1|dividend_type:discrete|endpoint_source:eod|expiration:20240328T000000|model_price:midpoint|n_steps:100|option_pricing_model:Binomial|right:C|strike:440|volatility_model:market with date range 2023-09-27 to 2024-03-28, missing dates within range: [], checked-missing dates: []
2026-05-03 21:51:22 [test] trade.datamanager.utils INFO: Sanitizing data from 2023-09-27 to 2024-03-28...
2026-05-03 21:51:22 [test] trade.datamanager.utils INFO: Using cached date range for 2023-09-27 00:00:00 - 2024-03-28 00:00:00 and option tick QQQ20240328C440
2026-05-03 21:51:22 [test] trade.datamanager.utils INFO: Covered range 2023-11-27 to 2024-02-08 does not span requested range 2023-09-27 to 2024-03-28 for key: symbol:QQQ|interval:eod|artifact_type:greeks|series_id:hist|dividend_type:discrete|endpoint_source:eod|expiration:20240328T000000|model_price:midpoint|option_pricing_model:Binomial|right:C|strike:440|volatility_model:market.

In [18]:
res.spot.timeseries

datetime
2023-09-27    349.836304
2023-09-28    352.762726
2023-09-29    353.018921
2023-10-02    355.965118
2023-10-03    349.718048
                 ...
2024-03-22    441.530945
2024-03-25    439.928497
2024-03-26    438.504211
2024-03-27    439.997772
2024-03-28    439.186676
Name: close, Length: 127, dtype: float64

In [20]:
retrieve_eod_ohlc(
    symbol="QQQ",
    start_date="2023-12-27",
    end_date="2024-02-08",
    strike=440.00,
    right="C",
    exp="2024-03-28",
    print_url=True,
)

2026-05-03 19:31:01 [test] dbase.DataAPI.ThetaData.switcher INFO: Switcher call retrieve_eod_ohlc -> v3

ThetaDataNotFound: Data not found for the given parameters: {'symbol': 'QQQ', 'start_date': '20231227', 'end_date': '20240208', 'expiration': '20240328', 'strike': '440.00', 'right': 'C', 'url': 'http://localhost:25503/v3/option/history/eod?symbol=QQQ&start_date=20231227&end_date=20240208&expiration=20240328&strike=440.00&right=C'}

In [ ]:
LIST_DATE_CACHE.clear()
_sync_date(
    symbol="QQQ",
    start_date="2023-12-27",
    end_date="2024-02-08",
    strike=440.00,
    right="C",
    expiration="2024-03-28"
)

2026-05-03 19:23:41 [test] trade.datamanager.utils INFO: Using cached date range for 2023-12-27 00:00:00 - 2024-02-08 00:00:00 and option tick QQQ20240328C440

(datetime.datetime(2023, 12, 27, 0, 0), datetime.datetime(2024, 2, 8, 0, 0))

In [38]:

## List all available dates for the given contract
d = list_dates(
    symbol="QQQ",
    exp="2024-03-28",
    strike=440,
    right="C",
    print_url=True)

## Filter the dates to only include those between 2023-12-27 and 2024-02-09
print(f"\nStart: {min(d)}, End: {max(d)}, Size of original list: {len(d)}")
print(f"Filtered dates within 2023-12-27 and 2024-02-09: {[d for d in d if '2023-12-27' <= d <= '2024-02-09']}")

2026-05-03 20:08:20 [test] dbase.DataAPI.ThetaData.switcher INFO: Switcher call list_dates -> v3
Request URL: http://localhost:25503/v3/option/list/dates/quote?symbol=QQQ&expiration=20240328&strike=440.00&right=C

Start: 2023-06-06, End: 2024-03-28, Size of original list: 176
Filtered dates within 2023-12-27 and 2024-02-09: ['2023-12-27', '2024-02-09']

In [37]:
d

array(['2023-12-27', '2023-12-28', '2023-12-29', '2024-01-02',
       '2024-01-03', '2024-01-04', '2024-01-05', '2024-01-08',
       '2024-01-09', '2024-01-10', '2024-01-11', '2024-01-12',
       '2024-01-16', '2024-01-17', '2024-01-18', '2024-01-19',
       '2024-01-22', '2024-01-23', '2024-01-24', '2024-01-25',
       '2024-01-26', '2024-01-29', '2024-01-30', '2024-01-31',
       '2024-02-01', '2024-02-02', '2024-02-05', '2024-02-06',
       '2024-02-07', '2024-02-08', '2024-02-09', '2024-02-12',
       '2024-02-13', '2024-02-14', '2024-02-15', '2024-02-16',
       '2024-02-20', '2024-02-21', '2024-02-22', '2024-02-23',
       '2024-02-26', '2024-02-27', '2024-02-28', '2024-02-29',
       '2024-03-01', '2024-03-04', '2024-03-05', '2024-03-06',
       '2024-03-07', '2024-03-08', '2024-03-11', '2024-03-12',
       '2024-03-13', '2024-03-14', '2024-03-15', '2024-03-18',
       '2024-03-19', '2024-03-20', '2024-03-21', '2024-03-22',
       '2024-03-25', '2024-03-26', '2024-03-27', '2024-03-28'],
      dtype=object)

In [39]:


c = list_contracts(
    symbol="QQQ",
    start_date="2024-03-28",
)

2026-05-03 20:17:25 [test] dbase.DataAPI.ThetaData.switcher INFO: Switcher call list_contracts -> v3

2026-05-03 20:17:26 [test] dbase.DataAPI.ThetaData.PatchProcessor WARNING: No patches registered for list_contracts

In [44]:
c[(c["right"] == "C") & (c["expiration"] == "2024-03-28") & (c["strike"] >= 430)].sort_values("strike")

                    root expiration  strike right
datetime
2024-03-28 16:00:00  QQQ 2024-03-28  430.00     C
2024-03-28 16:00:00  QQQ 2024-03-28  431.00     C
2024-03-28 16:00:00  QQQ 2024-03-28  432.00     C
2024-03-28 16:00:00  QQQ 2024-03-28  433.00     C
2024-03-28 16:00:00  QQQ 2024-03-28  434.00     C
2024-03-28 16:00:00  QQQ 2024-03-28  434.78     C
2024-03-28 16:00:00  QQQ 2024-03-28  435.00     C
2024-03-28 16:00:00  QQQ 2024-03-28  436.00     C
2024-03-28 16:00:00  QQQ 2024-03-28  437.00     C
2024-03-28 16:00:00  QQQ 2024-03-28  438.00     C
2024-03-28 16:00:00  QQQ 2024-03-28  439.00     C
2024-03-28 16:00:00  QQQ 2024-03-28  439.78     C
2024-03-28 16:00:00  QQQ 2024-03-28  440.00     C
2024-03-28 16:00:00  QQQ 2024-03-28  441.00     C
2024-03-28 16:00:00  QQQ 2024-03-28  442.00     C
2024-03-28 16:00:00  QQQ 2024-03-28  443.00     C
2024-03-28 16:00:00  QQQ 2024-03-28  444.00     C
2024-03-28 16:00:00  QQQ 2024-03-28  444.78     C
2024-03-28 16:00:00  QQQ 2024-03-28  445.00     C
2024-03-28 16:00:00  QQQ 2024-03-28  446.00     C
2024-03-28 16:00:00  QQQ 2024-03-28  447.00     C
2024-03-28 16:00:00  QQQ 2024-03-28  448.00     C
2024-03-28 16:00:00  QQQ 2024-03-28  449.00     C
2024-03-28 16:00:00  QQQ 2024-03-28  449.78     C
2024-03-28 16:00:00  QQQ 2024-03-28  450.00     C
2024-03-28 16:00:00  QQQ 2024-03-28  451.00     C
2024-03-28 16:00:00  QQQ 2024-03-28  452.00     C
2024-03-28 16:00:00  QQQ 2024-03-28  453.00     C
2024-03-28 16:00:00  QQQ 2024-03-28  454.00     C
2024-03-28 16:00:00  QQQ 2024-03-28  454.78     C
2024-03-28 16:00:00  QQQ 2024-03-28  455.00     C
2024-03-28 16:00:00  QQQ 2024-03-28  456.00     C
2024-03-28 16:00:00  QQQ 2024-03-28  457.00     C
2024-03-28 16:00:00  QQQ 2024-03-28  458.00     C
2024-03-28 16:00:00  QQQ 2024-03-28  459.00     C
2024-03-28 16:00:00  QQQ 2024-03-28  459.78     C
2024-03-28 16:00:00  QQQ 2024-03-28  460.00     C
2024-03-28 16:00:00  QQQ 2024-03-28  462.00     C
2024-03-28 16:00:00  QQQ 2024-03-28  463.00     C
2024-03-28 16:00:00  QQQ 2024-03-28  464.00     C
2024-03-28 16:00:00  QQQ 2024-03-28  464.78     C
2024-03-28 16:00:00  QQQ 2024-03-28  465.00     C
2024-03-28 16:00:00  QQQ 2024-03-28  468.00     C
2024-03-28 16:00:00  QQQ 2024-03-28  470.00     C
2024-03-28 16:00:00  QQQ 2024-03-28  475.00     C

In [ ]:
{
    "symbol": "AAPL",
    "start_date": "20230309",
    "end_date": "20230320",
    "expiration": "20241220",
    "strike": "245.00",
    "right": "C",
    "url": "http://localhost:25503/v3/option/history/eod?symbol=AAPL&start_date=20230309&end_date=20230320&expiration=20241220&strike=245.00&right=C",
}

In [10]:
symbol = "AAPL"
start_date = "2020-08-31"
end_date = "2020-12-31"
opt_params = {
    "strike": 385.0,
    "right": "C",
    "expiration": "2020-10-16",
}
OptionSpotDataManager(symbol=symbol).get_option_spot_timeseries(start_date=start_date,end_date=end_date,**opt_params,).timeseries

2026-04-29 22:59:29 [test] trade.datamanager.utils INFO: Using cached date range for 2020-08-31 00:00:00 - 2020-12-31 00:00:00 and option tick AAPL20201016C385
Synchronized date range for option spot timeseries: 2020-08-28 00:00:00 to 2020-08-28 00:00:00
2026-04-29 22:59:29 [test] trade.datamanager.utils INFO: Converting old cache data structure to new for key: symbol:AAPL|interval:eod|artifact_type:option_spot|series_id:hist|endpoint_source:EOD|expiration:20201016T000000|right:C|strike:385
2026-04-29 22:59:29 [test] trade.datamanager.utils INFO: No missing dates within cached data range for key: symbol:AAPL|interval:eod|artifact_type:option_spot|series_id:hist|endpoint_source:EOD|expiration:20201016T000000|right:C|strike:385.
2026-04-29 22:59:29 [test] trade.datamanager.utils INFO: Cache hit for timeseries data structure key: symbol:AAPL|interval:eod|artifact_type:option_spot|series_id:hist|endpoint_source:EOD|expiration:20201016T000000|right:C|strike:385
2026-04-29 22:59:29 [test] trade.datamanager.utils INFO: Sanitizing data from 2020-08-28 00:00:00 to 2020-08-28 00:00:00...
2026-04-29 22:59:29 [test] trade.datamanager.option_spot INFO: Cache hit for option spot timeseries key: symbol:AAPL|interval:eod|artifact_type:option_spot|series_id:hist|endpoint_source:EOD|expiration:20201016T000000|right:C|strike:385

,open,high,low,close,volume,bid_size,closebid,ask_size,closeask,midpoint,weighted_midpoint
datetime,,,,,,,,,,,
2020-08-28,123.45,123.45,120.0,120.3,3,7,117.5,8,118.85,118.175,118.22

In [ ]:
{
    "symbol": "NVDA",
    "start_date": "20240611",
    "end_date": "20240621",
    "expiration": "20240621",
    "strike": "600.00",
    "right": "C",
    "url": "http://localhost:25503/v3/option/history/eod?symbol=NVDA&start_date=20240611&end_date=20240621&expiration=20240621&strike=600.00&right=C",
}

In [29]:
# LIST_DATE_CACHE.clear()

_sync_date(
    symbol="NVDA",
    start_date="2024-06-11",
    end_date="2024-06-21",
    strike=600.0,
    right="C",
    expiration="20240621",
)

2026-05-03 19:42:09 [test] trade.datamanager.utils INFO: Fetching date range from Thetadata for NVDA20240621C600
2026-05-03 19:42:09 [test] dbase.DataAPI.ThetaData.switcher INFO: Switcher call list_dates -> v3
2026-05-03 19:42:11 [test] trade.datamanager.utils INFO: Calculated date range for option spot timeseries: 2024-06-11 00:00:00 to 2024-06-21 00:00:00
2026-05-03 19:42:11 [test] trade.datamanager.utils WARNING: Requested end_date 2024-06-21 is after available data. Adjusting to 2024-06-10.

(Timestamp('2024-06-10 00:00:00'), Timestamp('2024-06-10 00:00:00'))

In [9]:
sorted(list_dates("AAPL", "20201016", "C", 385.0))

2026-04-29 21:46:37 [test] dbase.DataAPI.ThetaData.switcher INFO: Switcher call list_dates -> v3

['2020-02-24',
 '2020-02-25',
 '2020-02-26',
 '2020-02-27',
 '2020-02-28',
 '2020-03-02',
 '2020-03-03',
 '2020-03-04',
 '2020-03-05',
 '2020-03-06',
 '2020-03-09',
 '2020-03-10',
 '2020-03-11',
 '2020-03-12',
 '2020-03-13',
 '2020-03-16',
 '2020-03-17',
 '2020-03-18',
 '2020-03-19',
 '2020-03-20',
 '2020-03-23',
 '2020-03-24',
 '2020-03-25',
 '2020-03-26',
 '2020-03-27',
 '2020-03-30',
 '2020-03-31',
 '2020-04-01',
 '2020-04-02',
 '2020-04-03',
 '2020-04-06',
 '2020-04-07',
 '2020-04-08',
 '2020-04-09',
 '2020-04-13',
 '2020-04-14',
 '2020-04-15',
 '2020-04-16',
 '2020-04-17',
 '2020-04-20',
 '2020-04-21',
 '2020-04-22',
 '2020-04-23',
 '2020-04-24',
 '2020-04-27',
 '2020-04-28',
 '2020-04-29',
 '2020-04-30',
 '2020-05-01',
 '2020-05-04',
 '2020-05-05',
 '2020-05-06',
 '2020-05-07',
 '2020-05-08',
 '2020-05-11',
 '2020-05-12',
 '2020-05-13',
 '2020-05-14',
 '2020-05-15',
 '2020-05-18',
 '2020-05-19',
 '2020-05-20',
 '2020-05-21',
 '2020-05-22',
 '2020-05-26',
 '2020-05-27',
 '2020-05-28',
 '2020-05-29',
 '2020-06-01',
 '2020-06-02',
 '2020-06-03',
 '2020-06-04',
 '2020-06-05',
 '2020-06-08',
 '2020-06-09',
 '2020-06-10',
 '2020-06-11',
 '2020-06-12',
 '2020-06-15',
 '2020-06-16',
 '2020-06-17',
 '2020-06-18',
 '2020-06-19',
 '2020-06-22',
 '2020-06-23',
 '2020-06-24',
 '2020-06-25',
 '2020-06-26',
 '2020-06-29',
 '2020-06-30',
 '2020-07-01',
 '2020-07-02',
 '2020-07-06',
 '2020-07-07',
 '2020-07-08',
 '2020-07-09',
 '2020-07-10',
 '2020-07-13',
 '2020-07-14',
 '2020-07-15',
 '2020-07-16',
 '2020-07-17',
 '2020-07-20',
 '2020-07-21',
 '2020-07-22',
 '2020-07-23',
 '2020-07-24',
 '2020-07-27',
 '2020-07-28',
 '2020-07-29',
 '2020-07-30',
 '2020-07-31',
 '2020-08-03',
 '2020-08-04',
 '2020-08-05',
 '2020-08-06',
 '2020-08-07',
 '2020-08-10',
 '2020-08-11',
 '2020-08-12',
 '2020-08-13',
 '2020-08-14',
 '2020-08-17',
 '2020-08-18',
 '2020-08-19',
 '2020-08-20',
 '2020-08-21',
 '2020-08-24',
 '2020-08-25',
 '2020-08-26',
 '2020-08-27',
 '2020-08-28']

In [4]:
c = list_contracts("AAPL", "2020-08-31")

2026-04-29 21:45:00 [test] dbase.DataAPI.ThetaData.switcher INFO: Switcher call list_contracts -> v3
2026-04-29 21:45:01 [test] dbase.DataAPI.ThetaData.PatchProcessor WARNING: No patches registered for list_contracts

In [6]:
c[c["strike"]==385]

Empty DataFrame
Columns: [root, expiration, strike, right]
Index: []

In [ ]:
{
    "symbol": "AAPL",
    "start_date": "20200831",
    "end_date": "20201016",
    "expiration": "20201016",
    "strike": "385.00",
    "right": "C",
    "url": "http://localhost:25503/v3/option/history/eod?symbol=AAPL&start_date=20200831&end_date=20201016&expiration=20201016&strike=385.00&right=C",
}

In [20]:
p={'symbol': 'NFLX', 'start_date': '20210827', 'end_date': '20210827',  'right': 'both', 'date': '20210827', 'time_of_day': '16:00:00.000', "end_time": "16:00:00.000"}

retrieve_chain_bulk(**p)

2026-04-26 19:41:40 [test] dbase.DataAPI.ThetaData.switcher INFO: Switcher call retrieve_chain_bulk -> v2

,Root,Expiration,Strike,Right,Bid_size,CloseBid,Ask_size,CloseAsk,Date,Midpoint,Weighted_midpoint
datetime,,,,,,,,,,,
2021-08-27,NFLX,2022-01-21,5.0,P,0,0.00,1,0.25,20210827,0.125,0.25000
2021-08-27,NFLX,2022-01-21,5.0,C,10,552.25,6,555.80,20210827,554.025,553.58125
2021-08-27,NFLX,2022-01-21,60.0,C,10,497.40,6,500.85,20210827,499.125,498.69375
2021-08-27,NFLX,2022-06-17,370.0,C,18,194.00,18,203.00,20210827,198.500,198.50000
2021-08-27,NFLX,2023-03-17,390.0,C,6,195.20,6,202.95,20210827,199.075,199.07500
...,...,...,...,...,...,...,...,...,...,...,...
2021-08-27,NFLX,2022-03-18,840.0,P,6,280.30,10,283.80,20210827,282.050,282.48750
2021-08-27,NFLX,2023-03-17,340.0,C,6,235.05,6,243.10,20210827,239.075,239.07500
2021-08-27,NFLX,2023-03-17,420.0,P,18,29.50,18,37.55,20210827,33.525,33.52500
2021-08-27,NFLX,2022-01-21,30.0,P,0,0.00,12,0.04,20210827,0.020,0.04000
2021-08-27,NFLX,2022-01-21,20.0,P,0,0.00,10,0.03,20210827,0.015,0.03000

In [12]:
# Data not found for the given parameters: {'symbol': 'AAPL', 'start_date': '20200826', 'end_date': '20200828', 'expiration': '20201016', 'strike': '96.25', 'right': 'C', 'url': 'http://localhost:25503/v3/option/history/eod?symbol=AAPL&start_date=20200826&end_date=20200828&expiration=20201016&strike=96.25&right=C'}
os.environ["THETADATA_USE_V3"] = "true"
d = list_dates(
    symbol='AAPL',
    exp='2020-10-16',
    right='C',
    strike=110.0,
)
d

2026-04-27 00:13:48 [test] dbase.DataAPI.ThetaData.switcher INFO: Switcher call list_dates -> v3

array(['2020-08-25', '2020-08-31', '2020-09-01', '2020-09-02',
       '2020-09-03', '2020-09-04', '2020-09-08', '2020-09-09',
       '2020-09-10', '2020-09-11', '2020-09-14', '2020-09-15',
       '2020-09-16', '2020-09-17', '2020-09-18', '2020-09-21',
       '2020-09-22', '2020-09-23', '2020-09-24', '2020-09-25',
       '2020-09-28', '2020-09-29', '2020-09-30', '2020-10-01',
       '2020-10-02', '2020-10-05', '2020-10-06', '2020-10-07',
       '2020-10-08', '2020-10-09', '2020-10-12', '2020-10-13',
       '2020-10-14', '2020-10-15', '2020-10-16'], dtype=object)

In [20]:
from trade.datamanager.utils.date import LIST_DATE_CACHE
from trade.helpers.helper import generate_option_tick_new
from trade.datamanager.option_spot import OptionSpotDataManager
from dbase.DataAPI.ThetaData import list_dates, set_use_proxy, retrieve_chain_bulk, list_contracts
len(LIST_DATE_CACHE.keys())
set_use_proxy("")
opt = generate_option_tick_new(
    symbol='AAPL',
    right='C',
    exp='2020-10-16',
    strike=96.25,
)
dm = OptionSpotDataManager("AAPL")
f = dm.get_option_spot_timeseries(
    start_date='2020-08-26',
    end_date='2020-09-28',
    expiration='2020-10-16',
    right='C',
    strike=100,
)

2026-04-26 21:22:01 [test] dbase.DataAPI.ThetaData.proxy INFO: Proxy URL has been unset.
2026-04-26 21:22:01 [test] trade.datamanager.utils INFO: Fetching date range from Thetadata for AAPL20201016C100
2026-04-26 21:22:01 [test] dbase.DataAPI.ThetaData.switcher INFO: Switcher call list_dates -> v3
2026-04-26 21:22:02 [test] trade.datamanager.utils INFO: Converting old cache data structure to new for key: symbol:AAPL|interval:eod|artifact_type:option_spot|series_id:hist|endpoint_source:EOD|expiration:20201016T000000|right:C|strike:100
2026-04-26 21:22:02 [test] trade.datamanager.utils INFO: No missing dates within requested range for key symbol:AAPL|interval:eod|artifact_type:option_spot|series_id:hist|endpoint_source:EOD|expiration:20201016T000000|right:C|strike:100. Fully covered: True
2026-04-26 21:22:02 [test] trade.datamanager.utils INFO: Cache hit for timeseries data structure key: symbol:AAPL|interval:eod|artifact_type:option_spot|series_id:hist|endpoint_source:EOD|expiration:20201016T000000|right:C|strike:100
2026-04-26 21:22:02 [test] trade.datamanager.utils INFO: Sanitizing data from 2020-08-31 00:00:00 to 2020-09-28 00:00:00...
2026-04-26 21:22:02 [test] trade.datamanager.option_spot INFO: Cache hit for option spot timeseries key: symbol:AAPL|interval:eod|artifact_type:option_spot|series_id:hist|endpoint_source:EOD|expiration:20201016T000000|right:C|strike:100

In [21]:
f.timeseries

,open,high,low,close,volume,bid_size,closebid,ask_size,closeask,midpoint,weighted_midpoint
datetime,,,,,,,,,,,
2020-08-31,27.48,31.73,27.48,30.50,1937,2,29.60,9,31.40,30.500,31.072727
2020-09-01,33.50,35.43,31.80,35.27,462,57,33.95,1,35.45,34.700,33.975862
2020-09-02,37.73,37.73,29.00,32.73,3310,10,31.60,10,33.70,32.650,32.650000
2020-09-03,28.80,30.15,23.15,23.50,901,4,23.00,2,25.00,24.000,23.666667
2020-09-04,23.15,25.30,15.80,23.40,2586,16,22.80,10,23.40,23.100,23.030769
2020-09-08,17.00,21.30,15.93,15.93,1127,2,15.25,1,16.25,15.750,15.583333
2020-09-09,18.80,20.50,18.00,19.12,377,56,18.75,55,19.05,18.900,18.898649
2020-09-10,20.70,20.75,14.95,15.80,2566,20,15.20,1,16.35,15.775,15.254762
2020-09-11,16.60,16.60,12.60,14.20,2085,70,13.95,12,14.25,14.100,13.993902
2020-09-14,16.10,17.10,14.50,16.80,1200,16,16.45,20,16.70,16.575,16.588889
2020-09-15,18.72,19.00,15.25,16.76,995,64,16.60,26,16.80,16.700,16.657778
2020-09-16,16.70,16.70,13.92,14.00,1197,17,13.80,13,14.00,13.900,13.886667
2020-09-17,12.96,13.83,11.50,12.45,1523,11,12.25,138,12.60,12.425,12.574161
2020-09-18,12.40,12.40,9.50,9.60,2855,60,9.55,60,9.85,9.700,9.700000
2020-09-21,8.10,12.18,7.50,12.18,2365,55,12.10,55,12.35,12.225,12.225000
2020-09-22,13.85,13.85,11.35,13.35,1681,91,13.05,21,13.35,13.200,13.106250
2020-09-23,12.90,13.30,9.49,9.77,988,18,9.65,18,9.95,9.800,9.800000
2020-09-24,8.45,11.85,8.32,10.36,908,10,10.20,31,10.40,10.300,10.351220
2020-09-25,10.68,13.40,9.95,13.33,853,70,13.10,30,13.45,13.275,13.205000
2020-09-28,15.81,15.81,13.70,15.45,426,141,15.35,20,15.55,15.450,15.374845

In [19]:
LIST_DATE_CACHE.clear()

2

In [1]:
from dbase.DataAPI.ThetaData.patches.main import ThetaDataPatchProcessor
from dbase.DataAPI.ThetaData.patches import ThetaDataPatchProcessor as ThetaDataPatchProcessorV3
ThetaDataPatchProcessorV3 == ThetaDataPatchProcessor
# ThetaDataPatchProcessor.PATCH_FUNCTIONS

/Users/chiemelienwanisobi/miniconda3/envs/openbb_new_use/lib/python3.11/site-packages/requests/__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(

2026-04-26 20:49:07 trade.helpers.Logging INFO: Logging Root Directory: /Users/chiemelienwanisobi/cloned_repos/FinanceDatabase/logs
2026-04-26 20:49:07 [test] trade.helpers.clear_cache INFO: No expired caches to delete on 2026-04-26.
2026-04-26 20:49:08 [test] dbase.DataAPI.ThetaData.proxy INFO: Refreshed proxy URL: http://34.229.99.136:5500/thetadata
2026-04-26 20:49:08 [test] dbase.DataAPI.ThetaData.proxy INFO: Using Proxy URL: http://34.229.99.136:5500/thetadata
Registering patch for list_dates
Registering patch for list_dates with function _remove_incorrect_date_for_option

True

In [ ]:
ThetaDataPatchProcessor.setup()

Registering patch for list_dates with function _remove_incorrect_date_for_option

True

In [5]:
ThetaDataPatchProcessor.PATCH_FUNCTIONS

{'list_dates': [<function dbase.DataAPI.ThetaData.patches.p1._remove_incorrect_date_for_option(result: Union[List[str], numpy.ndarray], symbol: str, exp: str, right: str, strike: float, *args, **kwargs) -> Union[List[str], numpy.ndarray]>]}

In [6]:

ThetaDataPatchProcessorV3.PATCH_FUNCTIONS

{'list_dates': [<function dbase.DataAPI.ThetaData.patches.p1._remove_incorrect_date_for_option(result: Union[List[str], numpy.ndarray], symbol: str, exp: str, right: str, strike: float, *args, **kwargs) -> Union[List[str], numpy.ndarray]>]}

In [56]:
ThetaDataPatchProcessor.setup()

Registering patch for list_dates with function _remove_incorrect_date_for_option

In [17]:
from typing import List, Union
import numpy as np

LIST_DATES_REMOVAL_BUCKET = {
    ("AAPL", "2020-10-16", "C", 96.25): "2020-08-25",
}



def _remove_incorrect_date(d: Union[List[str], np.ndarray], dt: str) -> List[str]:

    """
    Remove the incorrect date from the list of dates.
    Parameters    ----------
    d : List[str] or np.ndarray
        List of dates to be filtered.
    dt : str
        The date to be removed from the list.
    Returns    -------
    List[str]
        The list of dates with the incorrect date removed."""
    if dt in d:
        if isinstance(d, np.ndarray):
            d = d[d != dt]
        else:
            d.remove(dt)
        
    return d

def _remove_incorrect_date_for_option(
    symbol: str,
    exp: str,
    right: str,
    strike: float,
    d: Union[List[str], np.ndarray] = None,
    **kwargs
) -> Union[List[str], np.ndarray]:
    """
    Remove the incorrect date from the list of dates for a specific option contract.
    Parameters    ----------
    d : List[str] or np.ndarray
        List of dates to be filtered.
    symbol : str
        The symbol of the option contract.
    exp : str
        The expiration date of the option contract.
    right : str
        The right of the option contract (C or P).
    strike : float
        The strike price of the option contract.
    Returns    -------
    List[str] or np.ndarray
        The list of dates with the incorrect date removed."""
    
    key = (symbol, exp, right, strike)
    if d is None:
        d = list_dates(
            symbol=symbol,
            exp=exp,
            right=right,
            strike=strike,
        )
    
    if key in LIST_DATES_REMOVAL_BUCKET:
        dt = LIST_DATES_REMOVAL_BUCKET[key]
        return _remove_incorrect_date(d, dt)
    
    return d

# d = _remove_incorrect_date(d, "2020-08-25")
# d

In [33]:
import inspect
sig = inspect.signature(_remove_incorrect_date_for_option)
sig.parameters['kwargs'].kind

In [34]:
from pathlib import Path

NameError: name '__file__' is not defined

In [ ]:
from typing import Callable, Dict, List
class ThetaDataPatchProcessor:
    """
    Class responsible for applying patches to ThetaData API functions to handle known data issues.
    """
    PATCH_FUNCTIONS: Dict[str, List[Callable]] = {}

    @classmethod
    def register_patch(cls, func_name: str, patch_func: Callable):
        """
        Register a patch function for a specific ThetaData API function.
        Parameters    ----------
        func_name : str
            The name of the ThetaData API function to patch.
        patch_func : Callable
            The patch function to apply to the specified API function.
        """
        if func_name not in cls.PATCH_FUNCTIONS:
            cls.PATCH_FUNCTIONS[func_name] = []
        cls.PATCH_FUNCTIONS[func_name].append(patch_func)

    @classmethod
    def apply_patches(cls, func_name: str, *args, **kwargs):
        """
        Apply all registered patches for a specific ThetaData API function.
        Parameters    ----------
        func_name : str
            The name of the ThetaData API function to apply patches to.
        *args
            Positional arguments to pass to the patch functions.
        **kwargs
            Keyword arguments to pass to the patch functions.
        Returns    -------
        The result of applying the patches, if any, or None if no patches are registered."""
        if func_name in cls.PATCH_FUNCTIONS:
            for patch_func in cls.PATCH_FUNCTIONS[func_name]:
                result = patch_func(*args, **kwargs)
                if result is not None:
                    return result
        return None

In [25]:
c = list_contracts(
    symbol='AAPL',
    start_date='2020-08-25',
)
c[c["strike"] == 96.25]

2026-04-26 19:46:00 [test] dbase.DataAPI.ThetaData.switcher INFO: Switcher call list_contracts -> v2

      root  expiration  strike right
2994  AAPL    20200828   96.25     C
2995  AAPL    20200828   96.25     P
3008  AAPL    20200918   96.25     C
3009  AAPL    20200918   96.25     P
3024  AAPL    20201120   96.25     P
3025  AAPL    20201120   96.25     C
3074  AAPL    20210416   96.25     P
3075  AAPL    20210416   96.25     C
3890  AAPL    20200911   96.25     C
3891  AAPL    20200911   96.25     P
3898  AAPL    20201002   96.25     C
3899  AAPL    20201002   96.25     P
3935  AAPL    20210115   96.25     P
3936  AAPL    20210115   96.25     C
3958  AAPL    20210319   96.25     P
3959  AAPL    20210319   96.25     C
4178  AAPL    20200904   96.25     C
4179  AAPL    20200904   96.25     P
4184  AAPL    20200925   96.25     C
4185  AAPL    20200925   96.25     P
4198  AAPL    20201016   96.25     C
4199  AAPL    20201016   96.25     P

In [8]:
d

array(['2020-08-25', '2020-08-31', '2020-09-01', '2020-09-02',
       '2020-09-03', '2020-09-04', '2020-09-08', '2020-09-09',
       '2020-09-10', '2020-09-11', '2020-09-14', '2020-09-15',
       '2020-09-16', '2020-09-17', '2020-09-18', '2020-09-21',
       '2020-09-22', '2020-09-23', '2020-09-24', '2020-09-25',
       '2020-09-28', '2020-09-29', '2020-09-30', '2020-10-01',
       '2020-10-02', '2020-10-05', '2020-10-06', '2020-10-07',
       '2020-10-08', '2020-10-09', '2020-10-12', '2020-10-13',
       '2020-10-14', '2020-10-15', '2020-10-16'], dtype=object)